//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseParts
    {
        public int WarehouseID { get; set; }
        public int PartsID { get; set; }
        public int Count { get; set; }
    
        public virtual Parts Parts { get; set; }
        public virtual WareHouse WareHouse { get; set; }
    }
}
